const ACTION_DATA_TYPE_DATA = "data";
const ACTION_DATA_TYPE_PAGER = "pager";
const ACTION_DATA_TYPE_SORTER = "sorter";
const ACTION_DATA_TYPE_FILTER = "filter";
const ACTION_DATA_TYPE_SEARCH = "search";
const ACTION_DATA_TYPE_RETURN = "return";

const ACTION_DATA_TYPES = Object.freeze({
    DATA: ACTION_DATA_TYPE_DATA,
    PAGER: ACTION_DATA_TYPE_PAGER,
    SORTER: ACTION_DATA_TYPE_SORTER,
    FILTER: ACTION_DATA_TYPE_FILTER,
    SEARCH: ACTION_DATA_TYPE_SEARCH,
    RETURN: ACTION_DATA_TYPE_RETURN,
});

module.exports.ACTION_DATA_TYPES = ACTION_DATA_TYPES;
module.exports.ACTION_DATA_TYPES_VALUES = Object.values(ACTION_DATA_TYPES);
