const DEFAULT_USER_ROLE_FOR_ADMIN = "root";
const DEFAULT_USER_ROLE_FOR_GUEST = "guest";

const OBJECT_STRING = "[object String]";

const DOCUMENT_OWNER_FIELD_NAME = "owner";

module.exports = {
    OBJECT_STRING,
    DEFAULT_USER_ROLE_FOR_GUEST,
    DEFAULT_USER_ROLE_FOR_ADMIN,
    DOCUMENT_OWNER_FIELD_NAME,
};
